name: Apigee CI with apigeecli

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Apigeecli Version
        uses: docker://ghcr.io/apigee/apigeecli:latest
        id: apigeecli-version
        with:
          args: --version

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Set Variables depending on branch
      - name: Set Variables for [Main] branch
        if: github.ref == 'refs/heads/main'
        run: |
          echo "APIGEE_ORG=ssv-apigee-asm-demo" >> $GITHUB_ENV
          echo "APIGEE_ENV=eval" >> $GITHUB_ENV
          echo "WORKLOAD_IDENTITY_POOL=projects/769749427232/locations/global/workloadIdentityPools/apigee-ci-cd-pool/providers/apigee-ci-cd-pool-provider" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT=apigee-ci-cd@ssv-apigee-asm-demo.iam.gserviceaccount.com" >> $GITHUB_ENV

      - name: Set Variables for [Prod] branch
        if: github.ref == 'refs/heads/prod'
        run: |
          echo "APIGEE_ORG=ssv-apigee-asm-demo" >> $GITHUB_ENV
          echo "APIGEE_ENV=eval" >> $GITHUB_ENV
          echo "WORKLOAD_IDENTITY_POOL=projects/769749427232/locations/global/workloadIdentityPools/apigee-ci-cd-pool/providers/apigee-ci-cd-pool-provider" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT=apigee-ci-cd@ssv-apigee-asm-demo.iam.gserviceaccount.com" >> $GITHUB_ENV

      - name: Set Variables for branch not [Main], not [Prod]
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/prod'
        run: |
          echo "APIGEE_ORG=ssv-apigee-asm-demo" >> $GITHUB_ENV
          echo "APIGEE_ENV=eval" >> $GITHUB_ENV
          echo "WORKLOAD_IDENTITY_POOL=projects/769749427232/locations/global/workloadIdentityPools/apigee-ci-cd-pool/providers/apigee-ci-cd-pool-provider" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT=apigee-ci-cd@ssv-apigee-asm-demo.iam.gserviceaccount.com" >> $GITHUB_ENV

      - name: Authenticate Google Cloud
        id: 'gcp-auth'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/769749427232/locations/global/workloadIdentityPools/apigee-ci-cd-pool/providers/apigee-ci-cd-pool-provider'
          service_account: 'apigee-ci-cd@ssv-apigee-asm-demo.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Access Apigee API
        run: |-
          curl https://apigee.googleapis.com/v1/organizations/${APIGEE_ORG} \
          --header "Authorization: Bearer ${{ steps.gcp-auth.outputs.access_token }}"