name: Apigee CI with apigeecli

# Controls when the workflow will run
on:
  push:
    inputs:
      org:
        description: 'Define org name'     
        required: true
        default: 'prod-org'
#env:
  #GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Apigeecli Version
        uses: docker://ghcr.io/apigee/apigeecli:latest
        id: apigeecli-version
        with:
          args: --version

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print
        run: |
        echo "Org: ${{ github.event.inputs.org }}" 

      # - name: Authenticate Google Cloud
      #   id: 'gcp-auth'
      #   uses: google-github-actions/auth@v1
      #   with:
      #     token_format: 'access_token'
      #     service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
