name: Apigee CI with apigeecli

# Controls when the workflow will run
on: push

#env:
  #GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    container:
      image: ghcr.io/apigee/apigeecli:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Apigeecli Version
        id: apigeecli-version
        run: |
          apigeecli --version

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Authenticate Google Cloud
      #   id: 'gcp-auth'
      #   uses: google-github-actions/auth@v1
      #   with:
      #     token_format: 'access_token'
      #     service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
